services:
  frontend:
    image: node:latest
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: tail -f /dev/null

  backend:
    image: php:latest
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    ports:
      - "80:80"
    command: tail -f /dev/null

  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  crypto:
    image: node:latest
    working_dir: /app
    volumes:
      - ./crypto:/app
    ports:
      - "4000:4000"
    command: tail -f /dev/null